import { AlterationEnum, DiatonicNoteEnum } from "@/constants";

export const C_MINOR_HARMONIC_SCALE: IScaleDegree[] = [
	{
		order: 1,
		degree: 1,
		name: DiatonicNoteEnum.C,
		alteration: AlterationEnum.natural,
		function: "tonic",
		octave: 4,
	},
	{
		order: 2,
		degree: 2,
		name: DiatonicNoteEnum.D,
		alteration: AlterationEnum.natural,
		function: "supertonic",
		octave: 4,
	},
	{
		order: 3,
		degree: 3,
		name: DiatonicNoteEnum.E,
		alteration: AlterationEnum.flat,
		function: "mediant",
		octave: 4,
	},
	{
		order: 4,
		degree: 4,
		name: DiatonicNoteEnum.F,
		alteration: AlterationEnum.natural,
		function: "subdominant",
		octave: 4,
	},
	{
		order: 5,
		degree: 5,
		name: DiatonicNoteEnum.G,
		alteration: AlterationEnum.natural,
		function: "dominant",
		octave: 4,
	},
	{
		order: 6,
		degree: 6,
		name: DiatonicNoteEnum.A,
		alteration: AlterationEnum.flat,
		function: "submediant",
		octave: 4,
	},
	{
		order: 7,
		degree: 7,
		name: DiatonicNoteEnum.B,
		alteration: AlterationEnum.natural,
		function: "leading tone",
		octave: 4,
	},
];

export const C_MINOR_MELODIC_ASC_SCALE: IScaleDegree[] = [
	{
		order: 1,
		degree: 1,
		name: DiatonicNoteEnum.C,
		alteration: AlterationEnum.natural,
		function: "tonic",
		octave: 4,
	},
	{
		order: 2,
		degree: 2,
		name: DiatonicNoteEnum.D,
		alteration: AlterationEnum.natural,
		function: "supertonic",
		octave: 4,
	},
	{
		order: 3,
		degree: 3,
		name: DiatonicNoteEnum.E,
		alteration: AlterationEnum.flat,
		function: "mediant",
		octave: 4,
	},
	{
		order: 4,
		degree: 4,
		name: DiatonicNoteEnum.F,
		alteration: AlterationEnum.natural,
		function: "subdominant",
		octave: 4,
	},
	{
		order: 5,
		degree: 5,
		name: DiatonicNoteEnum.G,
		alteration: AlterationEnum.natural,
		function: "dominant",
		octave: 4,
	},
	{
		order: 6,
		degree: 6,
		name: DiatonicNoteEnum.A,
		alteration: AlterationEnum.natural,
		function: "submediant",
		octave: 4,
	},
	{
		order: 7,
		degree: 7,
		name: DiatonicNoteEnum.B,
		alteration: AlterationEnum.natural,
		function: "leading tone",
		octave: 4,
	},
];

export const C_MINOR_MELODIC_DESC_SCALE: IScaleDegree[] = [
	{
		order: 1,
		degree: 1,
		name: DiatonicNoteEnum.C,
		alteration: AlterationEnum.natural,
		function: "tonic",
		octave: 4,
	},
	{
		order: 2,
		degree: 2,
		name: DiatonicNoteEnum.D,
		alteration: AlterationEnum.natural,
		function: "supertonic",
		octave: 4,
	},
	{
		order: 3,
		degree: 3,
		name: DiatonicNoteEnum.E,
		alteration: AlterationEnum.flat,
		function: "mediant",
		octave: 4,
	},
	{
		order: 4,
		degree: 4,
		name: DiatonicNoteEnum.F,
		alteration: AlterationEnum.natural,
		function: "subdominant",
		octave: 4,
	},
	{
		order: 5,
		degree: 5,
		name: DiatonicNoteEnum.G,
		alteration: AlterationEnum.natural,
		function: "dominant",
		octave: 4,
	},
	{
		order: 6,
		degree: 6,
		name: DiatonicNoteEnum.A,
		alteration: AlterationEnum.flat,
		function: "submediant",
		octave: 4,
	},
	{
		order: 7,
		degree: 7,
		name: DiatonicNoteEnum.B,
		alteration: AlterationEnum.flat,
		function: "leading tone",
		octave: 4,
	},
];
