import { AlterationEnum, DiatonicNoteEnum } from "../../constants.js";
import type { IScaleDegree } from "../../types/index.js";

export const C_MAJOR_SCALE: IScaleDegree[] = [
  {
    order: 1,
    degree: 1,
    name: DiatonicNoteEnum.C,
    alteration: AlterationEnum.natural,
    function: "tonic",
    octave: 2,
  },
  {
    order: 2,
    degree: 2,
    name: DiatonicNoteEnum.D,
    alteration: AlterationEnum.natural,
    function: "supertonic",
    octave: 2,
  },
  {
    order: 3,
    degree: 3,
    name: DiatonicNoteEnum.E,
    alteration: AlterationEnum.natural,
    function: "mediant",
    octave: 2,
  },
  {
    order: 4,
    degree: 4,
    name: DiatonicNoteEnum.F,
    alteration: AlterationEnum.natural,
    function: "subdominant",
    octave: 2,
  },
  {
    order: 5,
    degree: 5,
    name: DiatonicNoteEnum.G,
    alteration: AlterationEnum.natural,
    function: "dominant",
    octave: 2,
  },
  {
    order: 6,
    degree: 6,
    name: DiatonicNoteEnum.A,
    alteration: AlterationEnum.natural,
    function: "submediant",
    octave: 2,
  },
  {
    order: 7,
    degree: 7,
    name: DiatonicNoteEnum.B,
    alteration: AlterationEnum.natural,
    function: "leading tone",
    octave: 2,
  },
];

export const G_MAJOR_SCALE: IScaleDegree[] = [
  {
    order: 1,
    degree: 1,
    name: DiatonicNoteEnum.G,
    alteration: AlterationEnum.natural,
    function: "tonic",
    octave: 2,
  },
  {
    order: 2,
    degree: 2,
    name: DiatonicNoteEnum.A,
    alteration: AlterationEnum.natural,
    function: "supertonic",
    octave: 2,
  },
  {
    order: 3,
    degree: 3,
    name: DiatonicNoteEnum.B,
    alteration: AlterationEnum.natural,
    function: "mediant",
    octave: 2,
  },
  {
    order: 4,
    degree: 4,
    name: DiatonicNoteEnum.C,
    alteration: AlterationEnum.natural,
    function: "subdominant",
    octave: 3,
  },
  {
    order: 5,
    degree: 5,
    alteration: AlterationEnum.natural,
    name: DiatonicNoteEnum.D,
    function: "dominant",
    octave: 3,
  },
  {
    order: 6,
    degree: 6,
    name: DiatonicNoteEnum.E,
    alteration: AlterationEnum.natural,
    function: "submediant",
    octave: 3,
  },
  {
    order: 7,
    degree: 7,
    name: DiatonicNoteEnum.F,
    alteration: AlterationEnum.sharp,
    function: "leading tone",
    octave: 3,
  },
];

export const D_MAJOR_SCALE: IScaleDegree[] = [
  {
    order: 1,
    degree: 1,
    name: DiatonicNoteEnum.D,
    alteration: AlterationEnum.natural,
    function: "tonic",
    octave: 4,
  },
  {
    order: 2,
    degree: 2,
    name: DiatonicNoteEnum.E,
    alteration: AlterationEnum.natural,
    function: "supertonic",
    octave: 4,
  },
  {
    order: 3,
    degree: 3,
    name: DiatonicNoteEnum.F,
    alteration: AlterationEnum.sharp,
    function: "mediant",
    octave: 4,
  },
  {
    order: 4,
    degree: 4,
    name: DiatonicNoteEnum.G,
    alteration: AlterationEnum.natural,
    function: "subdominant",
    octave: 4,
  },
  {
    order: 5,
    degree: 5,
    alteration: AlterationEnum.natural,
    name: DiatonicNoteEnum.A,
    function: "dominant",
    octave: 4,
  },
  {
    order: 6,
    degree: 6,
    name: DiatonicNoteEnum.B,
    alteration: AlterationEnum.natural,
    function: "submediant",
    octave: 4,
  },
  {
    order: 7,
    degree: 7,
    name: DiatonicNoteEnum.C,
    alteration: AlterationEnum.sharp,
    function: "leading tone",
    octave: 5,
  },
];

export const E_FLAT_MAJOR_SCALE: IScaleDegree[] = [
  {
    order: 1,
    degree: 1,
    name: DiatonicNoteEnum.E,
    alteration: AlterationEnum.flat,
    function: "tonic",
    octave: 4,
  },
  {
    order: 2,
    degree: 2,
    name: DiatonicNoteEnum.F,
    alteration: AlterationEnum.natural,
    function: "supertonic",
    octave: 4,
  },
  {
    order: 3,
    degree: 3,
    name: DiatonicNoteEnum.G,
    alteration: AlterationEnum.natural,
    function: "mediant",
    octave: 4,
  },
  {
    order: 4,
    degree: 4,
    name: DiatonicNoteEnum.A,
    alteration: AlterationEnum.flat,
    function: "subdominant",
    octave: 4,
  },
  {
    order: 5,
    degree: 5,
    name: DiatonicNoteEnum.B,
    alteration: AlterationEnum.flat,
    function: "dominant",
    octave: 4,
  },
  {
    order: 6,
    degree: 6,
    name: DiatonicNoteEnum.C,
    alteration: AlterationEnum.natural,
    function: "submediant",
    octave: 5,
  },
  {
    order: 7,
    degree: 7,
    name: DiatonicNoteEnum.D,
    alteration: AlterationEnum.natural,
    function: "leading tone",
    octave: 5,
  },
];

export const F_MAJOR_SCALE: IScaleDegree[] = [
  {
    order: 1,
    degree: 1,
    name: DiatonicNoteEnum.F,
    alteration: AlterationEnum.natural,
    function: "tonic",
    octave: 4,
  },
  {
    order: 2,
    degree: 2,
    name: DiatonicNoteEnum.G,
    alteration: AlterationEnum.natural,
    function: "supertonic",
    octave: 4,
  },
  {
    order: 3,
    degree: 3,
    name: DiatonicNoteEnum.A,
    alteration: AlterationEnum.natural,
    function: "mediant",
    octave: 4,
  },
  {
    order: 4,
    degree: 4,
    name: DiatonicNoteEnum.B,
    alteration: AlterationEnum.flat,
    function: "subdominant",
    octave: 4,
  },
  {
    order: 5,
    degree: 5,
    name: DiatonicNoteEnum.C,
    alteration: AlterationEnum.natural,
    function: "dominant",
    octave: 5,
  },
  {
    order: 6,
    degree: 6,
    name: DiatonicNoteEnum.D,
    alteration: AlterationEnum.natural,
    function: "submediant",
    octave: 5,
  },
  {
    order: 7,
    degree: 7,
    name: DiatonicNoteEnum.E,
    alteration: AlterationEnum.natural,
    function: "leading tone",
    octave: 5,
  },
];

export const C_SHARP_MAJOR_SCALE: IScaleDegree[] = [
  {
    order: 1,
    degree: 1,
    name: DiatonicNoteEnum.C,
    alteration: AlterationEnum.sharp,
    function: "tonic",
    octave: 4,
  },
  {
    order: 2,
    degree: 2,
    name: DiatonicNoteEnum.D,
    alteration: AlterationEnum.sharp,
    function: "supertonic",
    octave: 4,
  },
  {
    order: 3,
    degree: 3,
    name: DiatonicNoteEnum.E,
    alteration: AlterationEnum.sharp,
    function: "mediant",
    octave: 4,
  },
  {
    order: 4,
    degree: 4,
    name: DiatonicNoteEnum.F,
    alteration: AlterationEnum.sharp,
    function: "subdominant",
    octave: 4,
  },
  {
    order: 5,
    degree: 5,
    name: DiatonicNoteEnum.G,
    alteration: AlterationEnum.sharp,
    function: "dominant",
    octave: 4,
  },
  {
    order: 6,
    degree: 6,
    name: DiatonicNoteEnum.A,
    alteration: AlterationEnum.sharp,
    function: "submediant",
    octave: 4,
  },
  {
    order: 7,
    degree: 7,
    name: DiatonicNoteEnum.B,
    alteration: AlterationEnum.sharp,
    function: "leading tone",
    octave: 4,
  },
];

export const C_MAJOR_SCALE_3_OCTAVES = [
  {
    order: 1,
    degree: 1,
    name: DiatonicNoteEnum.C,
    alteration: AlterationEnum.natural,
    function: "tonic",
    octave: 2,
  },
  {
    order: 2,
    degree: 2,
    name: DiatonicNoteEnum.D,
    alteration: AlterationEnum.natural,
    function: "supertonic",
    octave: 2,
  },
  {
    order: 3,
    degree: 3,
    name: DiatonicNoteEnum.E,
    alteration: AlterationEnum.natural,
    function: "mediant",
    octave: 2,
  },
  {
    order: 4,
    degree: 4,
    name: DiatonicNoteEnum.F,
    alteration: AlterationEnum.natural,
    function: "subdominant",
    octave: 2,
  },
  {
    order: 5,
    degree: 5,
    name: DiatonicNoteEnum.G,
    alteration: AlterationEnum.natural,
    function: "dominant",
    octave: 2,
  },
  {
    order: 6,
    degree: 6,
    name: DiatonicNoteEnum.A,
    alteration: AlterationEnum.natural,
    function: "submediant",
    octave: 2,
  },
  {
    order: 7,
    degree: 7,
    name: DiatonicNoteEnum.B,
    alteration: AlterationEnum.natural,
    function: "leading tone",
    octave: 2,
  },
  {
    order: 8,
    degree: 1,
    name: DiatonicNoteEnum.C,
    alteration: AlterationEnum.natural,
    function: "tonic",
    octave: 3,
  },
  {
    order: 9,
    degree: 2,
    name: DiatonicNoteEnum.D,
    alteration: AlterationEnum.natural,
    function: "supertonic",
    octave: 3,
  },
  {
    order: 10,
    degree: 3,
    name: DiatonicNoteEnum.E,
    alteration: AlterationEnum.natural,
    function: "mediant",
    octave: 3,
  },
  {
    order: 11,
    degree: 4,
    name: DiatonicNoteEnum.F,
    alteration: AlterationEnum.natural,
    function: "subdominant",
    octave: 3,
  },
  {
    order: 12,
    degree: 5,
    name: DiatonicNoteEnum.G,
    alteration: AlterationEnum.natural,
    function: "dominant",
    octave: 3,
  },
  {
    order: 13,
    degree: 6,
    name: DiatonicNoteEnum.A,
    alteration: AlterationEnum.natural,
    function: "submediant",
    octave: 3,
  },
  {
    order: 14,
    degree: 7,
    name: DiatonicNoteEnum.B,
    alteration: AlterationEnum.natural,
    function: "leading tone",
    octave: 3,
  },
  {
    order: 15,
    degree: 1,
    name: DiatonicNoteEnum.C,
    alteration: AlterationEnum.natural,
    function: "tonic",
    octave: 4,
  },
  {
    order: 16,
    degree: 2,
    name: DiatonicNoteEnum.D,
    alteration: AlterationEnum.natural,
    function: "supertonic",
    octave: 4,
  },
  {
    order: 17,
    degree: 3,
    name: DiatonicNoteEnum.E,
    alteration: AlterationEnum.natural,
    function: "mediant",
    octave: 4,
  },
  {
    order: 18,
    degree: 4,
    name: DiatonicNoteEnum.F,
    alteration: AlterationEnum.natural,
    function: "subdominant",
    octave: 4,
  },
  {
    order: 19,
    degree: 5,
    name: DiatonicNoteEnum.G,
    alteration: AlterationEnum.natural,
    function: "dominant",
    octave: 4,
  },
  {
    order: 20,
    degree: 6,
    name: DiatonicNoteEnum.A,
    alteration: AlterationEnum.natural,
    function: "submediant",
    octave: 4,
  },
  {
    order: 21,
    degree: 7,
    name: DiatonicNoteEnum.B,
    alteration: AlterationEnum.natural,
    function: "leading tone",
    octave: 4,
  },
  {
    order: 22,
    degree: 1,
    name: DiatonicNoteEnum.C,
    alteration: AlterationEnum.natural,
    function: "tonic",
    octave: 5,
  },
];

export const C_MAJOR_SCALE_STARTING_ON_A = [
  {
    order: 1,
    degree: 6,
    name: DiatonicNoteEnum.A,
    alteration: AlterationEnum.natural,
    function: "submediant",
    octave: 1,
  },
  {
    order: 2,
    degree: 7,
    name: DiatonicNoteEnum.B,
    alteration: AlterationEnum.natural,
    function: "leading tone",
    octave: 1,
  },
  {
    order: 3,
    degree: 1,
    name: DiatonicNoteEnum.C,
    alteration: AlterationEnum.natural,
    function: "tonic",
    octave: 2,
  },
  {
    order: 4,
    degree: 2,
    name: DiatonicNoteEnum.D,
    alteration: AlterationEnum.natural,
    function: "supertonic",
    octave: 2,
  },
  {
    order: 5,
    degree: 3,
    name: DiatonicNoteEnum.E,
    alteration: AlterationEnum.natural,
    function: "mediant",
    octave: 2,
  },
  {
    order: 6,
    degree: 4,
    name: DiatonicNoteEnum.F,
    alteration: AlterationEnum.natural,
    function: "subdominant",
    octave: 2,
  },
  {
    order: 7,
    degree: 5,
    name: DiatonicNoteEnum.G,
    alteration: AlterationEnum.natural,
    function: "dominant",
    octave: 2,
  },
];

export const C_MAJOR_SCALE_STARTING_ON_A_3_OCTAVES = [
  {
    order: 1,
    degree: 1,
    name: DiatonicNoteEnum.A,
    alteration: AlterationEnum.natural,
    function: "submediant",
    octave: 1,
  },
  {
    order: 2,
    degree: 2,
    name: DiatonicNoteEnum.B,
    alteration: AlterationEnum.natural,
    function: "leading tone",
    octave: 1,
  },
  {
    order: 3,
    degree: 3,
    name: DiatonicNoteEnum.C,
    alteration: AlterationEnum.natural,
    function: "tonic",
    octave: 2,
  },
  {
    order: 4,
    degree: 4,
    name: DiatonicNoteEnum.D,
    alteration: AlterationEnum.natural,
    function: "supertonic",
    octave: 2,
  },
  {
    order: 5,
    degree: 5,
    name: DiatonicNoteEnum.E,
    alteration: AlterationEnum.natural,
    function: "mediant",
    octave: 2,
  },
  {
    order: 6,
    degree: 6,
    name: DiatonicNoteEnum.F,
    alteration: AlterationEnum.natural,
    function: "subdominant",
    octave: 2,
  },
  {
    order: 7,
    degree: 7,
    name: DiatonicNoteEnum.G,
    alteration: AlterationEnum.natural,
    function: "dominant",
    octave: 2,
  },
  {
    order: 1,
    degree: 1,
    name: DiatonicNoteEnum.A,
    alteration: AlterationEnum.natural,
    function: "submediant",
    octave: 2,
  },
  {
    order: 2,
    degree: 2,
    name: DiatonicNoteEnum.B,
    alteration: AlterationEnum.natural,
    function: "leading tone",
    octave: 2,
  },
  {
    order: 3,
    degree: 3,
    name: DiatonicNoteEnum.C,
    alteration: AlterationEnum.natural,
    function: "tonic",
    octave: 3,
  },
  {
    order: 4,
    degree: 4,
    name: DiatonicNoteEnum.D,
    alteration: AlterationEnum.natural,
    function: "supertonic",
    octave: 3,
  },
  {
    order: 5,
    degree: 5,
    name: DiatonicNoteEnum.E,
    alteration: AlterationEnum.natural,
    function: "mediant",
    octave: 3,
  },
  {
    order: 6,
    degree: 6,
    name: DiatonicNoteEnum.F,
    alteration: AlterationEnum.natural,
    function: "subdominant",
    octave: 3,
  },
  {
    order: 7,
    degree: 7,
    name: DiatonicNoteEnum.G,
    alteration: AlterationEnum.natural,
    function: "dominant",
    octave: 3,
  },
  {
    order: 1,
    degree: 1,
    name: DiatonicNoteEnum.A,
    alteration: AlterationEnum.natural,
    function: "submediant",
    octave: 3,
  },
  {
    order: 2,
    degree: 2,
    name: DiatonicNoteEnum.B,
    alteration: AlterationEnum.natural,
    function: "leading tone",
    octave: 3,
  },
  {
    order: 3,
    degree: 3,
    name: DiatonicNoteEnum.C,
    alteration: AlterationEnum.natural,
    function: "tonic",
    octave: 4,
  },
  {
    order: 4,
    degree: 4,
    name: DiatonicNoteEnum.D,
    alteration: AlterationEnum.natural,
    function: "supertonic",
    octave: 4,
  },
  {
    order: 5,
    degree: 5,
    name: DiatonicNoteEnum.E,
    alteration: AlterationEnum.natural,
    function: "mediant",
    octave: 4,
  },
  {
    order: 6,
    degree: 6,
    name: DiatonicNoteEnum.F,
    alteration: AlterationEnum.natural,
    function: "subdominant",
    octave: 4,
  },
  {
    order: 7,
    degree: 7,
    name: DiatonicNoteEnum.G,
    alteration: AlterationEnum.natural,
    function: "dominant",
    octave: 4,
  },
];

export const B_MINOR_MEL_ASC = [
  {
    order: 1,
    degree: 7,
    name: DiatonicNoteEnum.A,
    alteration: AlterationEnum.sharp,
    function: "leading tone",
    octave: 1,
  },
  {
    order: 2,
    degree: 1,
    name: DiatonicNoteEnum.B,
    alteration: AlterationEnum.natural,
    function: "tonic",
    octave: 1,
  },
  {
    order: 3,
    degree: 2,
    name: DiatonicNoteEnum.C,
    alteration: AlterationEnum.sharp,
    function: "supertonic",
    octave: 2,
  },
  {
    order: 4,
    degree: 3,
    name: DiatonicNoteEnum.D,
    alteration: AlterationEnum.natural,
    function: "mediant",
    octave: 2,
  },
  {
    order: 5,
    degree: 4,
    name: DiatonicNoteEnum.E,
    alteration: AlterationEnum.natural,
    function: "subdominant",
    octave: 2,
  },
  {
    order: 6,
    degree: 5,
    name: DiatonicNoteEnum.F,
    alteration: AlterationEnum.sharp,
    function: "dominant",
    octave: 2,
  },
  {
    order: 7,
    degree: 6,
    name: DiatonicNoteEnum.G,
    alteration: AlterationEnum.sharp,
    function: "submediant",
    octave: 2,
  },
];

export const C_MINOR_SCALE: IScaleDegree[] = [
  {
    order: 1,
    degree: 1,
    name: DiatonicNoteEnum.C,
    alteration: AlterationEnum.natural,
    function: "tonic",
    octave: 2,
  },
  {
    order: 2,
    degree: 2,
    name: DiatonicNoteEnum.D,
    alteration: AlterationEnum.natural,
    function: "supertonic",
    octave: 2,
  },
  {
    order: 3,
    degree: 3,
    name: DiatonicNoteEnum.E,
    alteration: AlterationEnum.flat,
    function: "mediant",
    octave: 2,
  },
  {
    order: 4,
    degree: 4,
    name: DiatonicNoteEnum.F,
    alteration: AlterationEnum.natural,
    function: "subdominant",
    octave: 2,
  },
  {
    order: 5,
    degree: 5,
    name: DiatonicNoteEnum.G,
    alteration: AlterationEnum.natural,
    function: "dominant",
    octave: 2,
  },
  {
    order: 6,
    degree: 6,
    name: DiatonicNoteEnum.A,
    alteration: AlterationEnum.flat,
    function: "submediant",
    octave: 2,
  },
  {
    order: 7,
    degree: 7,
    name: DiatonicNoteEnum.B,
    alteration: AlterationEnum.natural,
    function: "leading tone",
    octave: 2,
  },
];

export const Eb4_MINOR_MELODIC_ASCENDING: IScaleDegree[] = [
  {
    order: 1,
    degree: 1,
    name: DiatonicNoteEnum.E,
    alteration: AlterationEnum.flat,
    function: "tonic",
    octave: 4,
  },
  {
    order: 2,
    degree: 2,
    name: DiatonicNoteEnum.F,
    alteration: AlterationEnum.natural,
    function: "supertonic",
    octave: 4,
  },
  {
    order: 3,
    degree: 3,
    name: DiatonicNoteEnum.G,
    alteration: AlterationEnum.flat,
    function: "mediant",
    octave: 4,
  },
  {
    order: 4,
    degree: 4,
    name: DiatonicNoteEnum.A,
    alteration: AlterationEnum.flat,
    function: "subdominant",
    octave: 4,
  },
  {
    order: 5,
    degree: 5,
    name: DiatonicNoteEnum.B,
    alteration: AlterationEnum.flat,
    function: "dominant",
    octave: 4,
  },
  {
    order: 6,
    degree: 6,
    name: DiatonicNoteEnum.C,
    alteration: AlterationEnum.natural,
    function: "submediant",
    octave: 5,
  },
  {
    order: 7,
    degree: 7,
    name: DiatonicNoteEnum.D,
    alteration: AlterationEnum.natural,
    function: "leading tone",
    octave: 5,
  },
];
export const Eb_Minor_Harmonic_Scale = [
  {
    order: 1,
    degree: 1,
    name: DiatonicNoteEnum.E,
    alteration: AlterationEnum.flat,
    function: "tonic",
    octave: 2,
  },
  {
    order: 2,
    degree: 2,
    name: DiatonicNoteEnum.F,
    alteration: AlterationEnum.natural,
    function: "supertonic",
    octave: 2,
  },
  {
    order: 3,
    degree: 3,
    name: DiatonicNoteEnum.G,
    alteration: AlterationEnum.flat,
    function: "mediant",
    octave: 2,
  },
  {
    order: 4,
    degree: 4,
    name: DiatonicNoteEnum.A,
    alteration: AlterationEnum.flat,
    function: "subdominant",
    octave: 2,
  },
  {
    order: 5,
    degree: 5,
    name: DiatonicNoteEnum.B,
    alteration: AlterationEnum.flat,
    function: "dominant",
    octave: 2,
  },
  {
    order: 6,
    degree: 6,
    name: DiatonicNoteEnum.C,
    alteration: AlterationEnum.flat,
    function: "submediant",
    octave: 3,
  },
  {
    order: 7,
    degree: 7,
    name: DiatonicNoteEnum.D,
    alteration: AlterationEnum.natural, // Raised seventh
    function: "leading tone",
    octave: 3,
  },
];
