name: Build and Deploy

on:
  push:
    branches:
      - main  # or your preferred branch, e.g., 'master', 'dev', etc.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test

    - name: Build project
      run: npm run build  # Ensure this command correctly builds your project into the dist folder

    - name: Commit dist folder
      run: |
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add dist/
        git commit -m 'build'
        git push origin main  # Pushes the changes to the main branch (adjust the branch as needed)

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

