name: Build and Deploy

on:
  push:
    branches:
      - main  # or your preferred branch, e.g., 'master', 'dev', etc.

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22]  # Test against multiple Node.js versions

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}  # Use Node.js version from matrix

    - name: Cache npm dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm install

    - name: Run lint
      run: npm run lint  # Ensure you have a lint script in your package.json

    - name: Run tests
      run: npm test

    - name: Run build
      run: npm run build  # Ensure this command correctly builds your project

    - name: Deploy
      run: npm run deploy  # Use a deploy script or GitHub Pages for deployment
      env:
        GITHUB_TOKEN: ${{ secrets.MusicUtilitiesToken }}

    - name: Clean up
      run: |
        git config --global user.name "${antoine}"
        git config --global user.email "${antoine}@typedin.dev"
        git add dist/
        git commit -m 'build'
        git push origin main  # Pushes the changes to the main branch (adjust the branch as needed)
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.MusicUtilitiesToken }}
